Add documentation
octopusden/octopus-components-registry-service pull request #26
Opened 2023-11-08 16:06 UTC by CamaradeRoman

Resolves #25

2023-11-08 20:29 UTC, pgorbachev requested changes

2023-11-08 20:29 UTC, pgorbachev commented on docs/configuration.adoc
> +:header: Octopus Components Registry Configuration
Предлагаю убрать Octopus из заголовка

2023-11-08 20:29 UTC, pgorbachev commented on docs/configuration.adoc
> +vcs type = GIT
vcs type более не актуален, нужно удалить

2023-11-08 20:29 UTC, pgorbachev commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (default for all versions)
repositoryType более неакутален

2023-11-09 07:59 UTC, aryabokon requested changes

2023-11-09 07:59 UTC, aryabokon commented on build.gradle
> +        if (wikiProperties[it] == null) throw new Exception("`wiki.$it` property must be defined")
Мы везде бросаем такой Exception? Может IllegalArgumentException?

2023-11-09 07:59 UTC, aryabokon commented on docs/configuration.adoc
> +
нам точно нужно столько пустых строк?

2023-11-09 07:59 UTC, aryabokon commented on docs/images/icons/warning.png
Нужно использовать стандартный код `<ac:emoticon ac:name="warning"/>` , а не тащить картинки

2023-11-09 09:43 UTC, pgorbachev requested changes

2023-11-09 09:43 UTC, pgorbachev commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (for specific version range)
repositoryType удалить

2023-11-09 10:53 UTC, CamaradeRoman commented on docs/configuration.adoc
> +vcs type = GIT
@aryabokon @pgorbachev может имеет смысл вообще убрать эту секцию и сделать её отдельной локальной страницей в wiki?

2023-11-09 10:56 UTC, CamaradeRoman commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (default for all versions)
@pgorbachev в смысле неактуален? Поддержан ведь https://github.com/octopusden/octopus-components-registry-service/blob/fa682aec847bec22a8d6f50ab6a75b43b09f5aa5/component-resolver-api/src/main/java/org/octopusden/octopus/escrow/RepositoryType.java#L3

2023-11-09 11:01 UTC, CamaradeRoman commented on docs/configuration.adoc
> +
не нужно

2023-11-09 11:07 UTC, CamaradeRoman commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (for specific version range)
@pgorbachev фактически же это поддержано. Если нужно "скрыть" возможность подобного переопределения, то нужно удалять только вместе с vcsUrl. Такой вариант нам подходит?

2023-11-09 11:22 UTC, CamaradeRoman commented on build.gradle
> +        if (wikiProperties[it] == null) throw new Exception("`wiki.$it` property must be defined")
Хорошо

2023-11-09 11:23 UTC, CamaradeRoman commented on docs/configuration.adoc
> +:header: Octopus Components Registry Configuration
Убрано

2023-11-09 11:29 UTC, CamaradeRoman commented on docs/images/icons/warning.png
заменил image на font для icons

2023-11-09 12:33 UTC, aryabokon submitted a review, later dismissed
@CamaradeRoman, договоритесь с @pgorbachev

2023-11-09 12:33 UTC, aryabokon commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (for specific version range)
это документация для пользователя, ему надо давать то, что актуально, а не все

2023-11-09 12:48 UTC, CamaradeRoman commented on docs/configuration.adoc
> +vcs type = GIT
Пока убрал информацию о поддержке нескольких VCS типов. Считаем что должен быть GIT.

2023-11-09 12:48 UTC, CamaradeRoman commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (for specific version range)
Пока убрал информацию о поддержке нескольких VCS типов. Считаем что должен быть GIT.

2023-11-09 12:52 UTC, aryabokon commented on docs/configuration.adoc
> +** GIT repository release tag format
так тоже не надо :)

2023-11-09 13:00 UTC, aryabokon approved these changes

2023-11-09 15:52 UTC, pgorbachev commented on docs/configuration.adoc
> +           repositoryType = <version control system> // GIT, CVS or MERCURIAL. (default for all versions)
repositoryType вычисляется из vcsUrl, поэтому предлагаю упрощать документацию

2023-11-09 16:02 UTC, pgorbachev approved these changes

2023-11-09 16:03 UTC, pgorbachev commented
тесты прошли

2023-11-09 16:52 UTC, merged