Add field Component.buildSystem and method getComponentVersion
octopusden/octopus-components-registry-service pull request #41
Opened 2024-05-23 12:28 UTC by qu0d

2024-05-23 14:39 UTC, aryabokon requested changes

2024-05-23 14:39 UTC, aryabokon commented on components-registry-service-client/src/main/kotlin/org/octopusden/octopus/components/registry/client/impl/ClassicComponentsRegistryServiceClient.kt
> +    override fun getComponentVersion(componentKey: String, version: String) =
getComponent

2024-05-23 14:39 UTC, aryabokon commented on components-registry-service-client/src/test/kotlin/org/octopusden/octopus/components/registry/client/ComponentRegistryServiceClientTest.kt
> +    override fun getComponentVersion(component: String, version: String) =
getComponent

2024-05-23 14:39 UTC, aryabokon commented on components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/controller/BaseComponentController.kt
> +    fun getComponentVersion(
getComponent

2024-05-23 14:39 UTC, aryabokon commented on test-common/src/testFixtures/kotlin/org/octopusden/octopus/components/registry/test/BaseComponentsRegistryServiceTest.kt
> +        val actualComponent = getComponentVersion("TESTONE", "1")
а негативный сценарий?

2024-05-23 14:39 UTC, aryabokon commented on test-common/src/testFixtures/kotlin/org/octopusden/octopus/components/registry/test/BaseComponentsRegistryServiceTest.kt
> +    protected abstract fun getComponentVersion(component: String, version: String): ComponentV2
getComponent

2024-05-23 14:39 UTC, aryabokon commented on components-registry-service-server/src/test/kotlin/org/octopusden/octopus/components/registry/server/ComponentsRegistryServiceControllerTest.kt
> +    override fun getComponentVersion(component: String, version: String): ComponentV2 =
getComponent

2024-05-23 16:47 UTC, aryabokon requested changes

2024-05-23 16:47 UTC, aryabokon commented on components-registry-service-client/src/test/kotlin/org/octopusden/octopus/components/registry/client/ComponentRegistryServiceClientTest.kt
> +            componentsRegistryClient.getComponent("TESTONE-?", "1")
Было-бы правильно сделать негативный сценарий, когда компонент с таким именем есть, а версии нет

2024-05-24 11:36 UTC, qu0d commented on components-registry-service-client/src/test/kotlin/org/octopusden/octopus/components/registry/client/ComponentRegistryServiceClientTest.kt
> +            componentsRegistryClient.getComponent("TESTONE-?", "1")
Сделал

2024-05-27 10:27 UTC, CamaradeRoman commented on components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/controller/ComponentControllerV2.kt
> +            null -> null
Не надо так, параметр и возвращаемый тип не должны быть nullable.

Всегда можно написать escrowModuleConfig.buildSystem?.let { getBuildSystem(it) }

2024-05-27 10:31 UTC, CamaradeRoman commented on components-registry-service-core/src/main/kotlin/org/octopusden/octopus/components/registry/core/dto/DetailedComponent.kt
> +        result = 31 * result + (buildSystem?.hashCode() ?: 0)
Можно использовать метод Objects.hash()

2024-05-27 10:36 UTC, qu0d commented on components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/controller/ComponentControllerV2.kt
> +            null -> null
Done

2024-05-27 10:48 UTC, qu0d commented on components-registry-service-core/src/main/kotlin/org/octopusden/octopus/components/registry/core/dto/DetailedComponent.kt
> +        result = 31 * result + (buildSystem?.hashCode() ?: 0)
Оставлю для однообразия, как везде

2024-05-27 10:55 UTC, CamaradeRoman approved these changes

2024-05-27 11:13 UTC, pgorbachev approved these changes

2024-05-27 12:18 UTC, merged