Validation of distribution->docker field
octopusden/octopus-components-registry-service pull request #61
Opened 2024-10-22 12:46 UTC by ozonophore

2024-10-24 11:55 UTC, pgorbachev requested changes

2024-10-24 11:55 UTC, pgorbachev commented on component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidatorTest.groovy
> +        assert GroovySlurperConfigValidator.DOCKER_PATTERN.matcher("octopusden/octopus").matches()
Let's use static import for GroovySlurperConfigValidator

2024-10-24 11:55 UTC, pgorbachev commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    private static final String FILE_PATTERN = "file:/.+"
Я не сталкивался с рекомендациями, что сначала идут private, потом public константы. Кто это продвигает?

2024-10-24 17:49 UTC, ozonophore commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    private static final String FILE_PATTERN = "file:/.+"
вернул назад

2024-10-24 17:49 UTC, ozonophore commented on component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidatorTest.groovy
> +        assert GroovySlurperConfigValidator.DOCKER_PATTERN.matcher("octopusden/octopus").matches()
добавил impost static

2024-10-28 08:48 UTC, pgorbachev commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    public static final Pattern DOCKER_PATTERN = Pattern.compile("^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*\$")
Этот паттерн потом можно переиспользовать в dms-service?

2024-10-28 08:53 UTC, pgorbachev submitted a review, later dismissed

2024-10-28 09:34 UTC, ozonophore commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    public static final Pattern DOCKER_PATTERN = Pattern.compile("^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*\$")
Сейчас они одинаковые, но если/когда будет список образов шаблоны, скорей всего, станут разными

2024-10-28 09:56 UTC, aryabokon requested changes

2024-10-28 09:56 UTC, aryabokon commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    private void validateExpression(ConfigObject distributionSection, String key, Pattern pattern, EscrowExpressionContext expressionContext) {
ConfigObject distributionSection ...

2024-10-28 09:56 UTC, aryabokon commented on component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidatorTest.groovy
> +        assert !DOCKER_PATTERN.matcher("octopusden/octopus:builder:1.0").matches()
еще бы добавить валидный полный вариант, типа:
org.octopusden/octopus/image:1.0

2024-10-28 09:56 UTC, aryabokon commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +        validateExpression(distributionSection, "GAV", GAV_PATTERN, expressionContext)
эту функцию можно переиспользовать во всех местах, где есть паттерн матчинг? Если да, давай переиспользуем

2024-10-28 13:44 UTC, ozonophore commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
> +    private void validateExpression(ConfigObject distributionSection, String key, Pattern pattern, EscrowExpressionContext expressionContext) {
переименовал

2024-10-29 08:03 UTC, pgorbachev approved these changes

2024-10-29 10:15 UTC, aryabokon approved these changes

2024-10-29 10:23 UTC, merged