Bump releng-lib version
octopusden/octopus-components-registry-service pull request #8
Opened 2023-07-10 10:01 UTC by ozonophore

2023-07-10 12:11 UTC, CamaradeRoman approved these changes

2023-07-10 15:16 UTC, CamaradeRoman approved these changes

2023-07-19 14:11 UTC, aryabokon requested changes

2023-07-19 14:11 UTC, aryabokon commented on component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/resolvers/EscrowConfigurationLoaderTest.groovy
> +import static org.octopusden.octopus.escrow.TestConfigUtils.*
\*

2023-07-19 17:28 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/ComponentConfigDeserializer.java
> +        JiraComponentVersionRange.Builder builder = new JiraComponentVersionRange.Builder(versionNames)
С целью вынести логику из модели в билдер. Модель не должна содержать никакой логики

2023-07-19 17:30 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
Потому, что модель иммутабельна и геттеры лишние

2023-07-20 06:37 UTC, ozonophore commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/resolvers/JiraParametersResolver.groovy
> -        Objects.requireNonNull(escrowConfigurationLoader)
<img width="1206" alt="image" src="https://github.com/octopusden/octopus-components-registry-service/assets/5319103/c8548417-d70d-4f9a-9b88-1a764b08388d">
Как было и как стало. Видно, что во втором конструкторе в случае escrowConfigurationLoader == null упадет NPE.

2023-07-20 07:27 UTC, ozonophore commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/resolvers/JiraParametersResolver.groovy
> +                if (escrowModuleConfigMatcher.match(mavenArtifact, moduleConfig, numericVersionFactory, versionRangeFactory)) {
> Может быть стоит внести factory в конструктор escrowModuleConfigMatcher, а не в метод?

Перенес

2023-07-20 07:27 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/ComponentConfigDeserializer.java
> +import java.util.*;
> Мы не поддерживаем *, надо настройки IDE сделать, чтобы не схлопывал

поправил

2023-07-20 07:28 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +        public Builder(VersionNames versionNames) {
> 

поправил

2023-07-20 07:28 UTC, ozonophore commented on component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/resolvers/EscrowConfigurationLoaderTest.groovy
> +import static org.octopusden.octopus.escrow.TestConfigUtils.*
> *

поправил

2023-07-20 07:41 UTC, aryabokon commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
не буду настаивать, @pgorbachev , как считаешь?

2023-07-20 07:44 UTC, aryabokon approved these changes
@pgorbachev, посмотри, пожалуйста

2023-07-20 08:19 UTC, pgorbachev commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
@ozonophore , @aryabokon ,  1) я сторонник того, чтобы весь код был в едином стиле. У нас в других классах модели используются геттеры
2) если делаем рефакторинг (без изменения функциональности), лучше это выносить отдельным PR

2023-07-20 08:20 UTC, pgorbachev commented on component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/resolvers/JiraParametersResolver.groovy
> -        Objects.requireNonNull(escrowConfigurationLoader)
Вопрос читаемости - Objects.requiresNull явно говорит, что будет NPE.
Не принципиально

2023-07-20 08:25 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
> @ozonophore , @aryabokon , 1) я сторонник того, чтобы весь код был в едином стиле. У нас в других классах модели используются геттеры 2) если делаем рефакторинг (без изменения функциональности), лучше это выносить отдельным PR

Достаточно спорное утверждение, что весь код здесь выдержан в едином стиле. Данная правка затрагивает этот кусок кода и смысл тянуть какой то бойлерплейт не вижу

2023-07-20 08:49 UTC, aryabokon commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
я просто против отключения геттеров в java и вопрос даже не в стиле. А еще меня смущает, что builder позволяет создать класс недоинициализированным, что гораздо сложней сделать через конструктор

2023-07-20 09:26 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
> я просто против отключения геттеров в java и вопрос даже не в стиле. А еще меня смущает, что builder позволяет создать класс недоинициализированным, что гораздо сложней сделать через конструктор

Вернул геттеры.

2023-07-21 10:32 UTC, pgorbachev commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/ComponentConfigDeserializer.java
> +        JiraComponentVersionRange.Builder builder = new JiraComponentVersionRange.Builder(versionNames)
Предлагаю заменить Builder на Factory/Factory Method.
паттерн билдер предплолагает, что некоторые параметры.методы м.б. быть опциональными, поэтому Factory больше подходит и он также может содержать бизнес логику.

2023-07-24 04:57 UTC, ozonophore commented on component-resolver-api/src/main/java/org/octopusden/octopus/escrow/config/JiraComponentVersionRange.java
> +    public final String componentName;
Переделал на фабрику

2023-07-24 08:55 UTC, aryabokon approved these changes

2023-07-24 09:08 UTC, merged